"""improved models

Revision ID: 616959481981
Revises: 
Create Date: 2024-04-30 17:14:42.581765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616959481981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('is_RAG_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_task_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('setting', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_task_id'], ['evaluation_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('occupation', sa.String(length=80), nullable=False),
    sa.Column('last_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_task_id'], ['evaluation_task.id'], name='fk_user_last_task_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], name='fk_response_prompt_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_response_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('evaluator_type', sa.String(length=50), nullable=False),
    sa.Column('correctness', sa.Integer(), nullable=True),
    sa.Column('relevance', sa.Integer(), nullable=True),
    sa.Column('appropriateness', sa.Integer(), nullable=True),
    sa.Column('clarity', sa.Integer(), nullable=True),
    sa.Column('noanswer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation')
    op.drop_table('response')
    op.drop_table('user')
    op.drop_table('prompt')
    op.drop_table('evaluation_task')
    op.drop_table('category')
    # ### end Alembic commands ###
