"""empty message

Revision ID: db1e192d53db
Revises: aae00b76dcd0
Create Date: 2024-05-02 10:15:05.326120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1e192d53db'
down_revision = 'aae00b76dcd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_column('intent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intent', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
